import { config } from './config.js';
import { createScopedNullifier, createUserHash, getDomain, normalizeEmail } from './identity.js';

function ensureDemoUser(store, { email, nickname, trustLevel = 0, roles = [] }) {
  const normalizedEmail = normalizeEmail(email);
  const userHash = createUserHash(normalizedEmail, config.authSubjectSecret);
  const nullifier = createScopedNullifier(userHash, config.communityId, config.nullifierSecret);
  const user = store.upsertUser(userHash, getDomain(normalizedEmail), nullifier);

  if (!user.nickname) {
    store.setNickname(user.user_hash, nickname);
  }

  user.trust_level = trustLevel;
  user.roles = [...new Set([...user.roles, ...roles])];
  store.persistUser(user);
  return user;
}

function ensureSpace(store, name, allowedDomains) {
  const existing = [...store.spaces.values()].find((space) => {
    return space.name === name
      && JSON.stringify(space.allowed_domains) === JSON.stringify(allowedDomains);
  });

  return existing || store.createSpace(name, allowedDomains);
}

function ensurePost(store, userHash, spaceId, content) {
  const existing = [...store.posts.values()].find((post) => {
    return post.user_hash === userHash && post.space_id === spaceId && post.content === content;
  });

  return existing || store.createPost(userHash, spaceId, content);
}

function ensureComment(store, postId, userHash, content) {
  const existing = [...store.comments.values()].find((comment) => {
    return comment.post_id === postId && comment.user_hash === userHash && comment.content === content;
  });

  return existing || store.createComment(postId, userHash, content);
}

function ensureOpenCase(store, report, targetType, targetId, accusedHash) {
  const existing = store.findOpenCase(targetType, targetId);
  if (existing) {
    return existing;
  }

  return store.createModerationCase(targetType, targetId, accusedHash, [report.id]);
}

export function seedDemoData(store) {
  const moderator = ensureDemoUser(store, {
    email: 'moderator@example.edu',
    nickname: 'demo_moderator',
    trustLevel: 3,
    roles: ['moderator']
  });
  const juror = ensureDemoUser(store, {
    email: 'juror@example.edu',
    nickname: 'demo_juror',
    trustLevel: 2
  });
  const reporter = ensureDemoUser(store, {
    email: 'reporter@example.edu',
    nickname: 'demo_reporter',
    trustLevel: 2
  });
  const member = ensureDemoUser(store, {
    email: 'member@example.edu',
    nickname: 'demo_member',
    trustLevel: 1
  });
  const accused = ensureDemoUser(store, {
    email: 'accused@example.edu',
    nickname: 'demo_accused',
    trustLevel: 0
  });
  const orgMember = ensureDemoUser(store, {
    email: 'org-member@example.org',
    nickname: 'demo_org_member',
    trustLevel: 1
  });

  const publicSpace = store.spaces.get('public');
  const eduSpace = ensureSpace(store, 'Example Edu', ['example.edu']);
  const orgSpace = ensureSpace(store, 'Example Org', ['example.org']);

  const welcomePost = ensurePost(
    store,
    moderator.user_hash,
    publicSpace.id,
    'Welcome to the local UniAnon demo. Try posting, commenting, reporting, and jury voting.'
  );
  ensureComment(store, welcomePost.id, member.user_hash, 'This comment was generated by the demo seed.');

  const reviewPost = ensurePost(
    store,
    accused.user_hash,
    publicSpace.id,
    'Demo review item: report this post or vote on the existing governance case.'
  );
  ensurePost(
    store,
    member.user_hash,
    eduSpace.id,
    'Example.edu-only space post.'
  );
  ensurePost(
    store,
    orgMember.user_hash,
    orgSpace.id,
    'Example.org-only space post.'
  );

  const { report } = store.createReport(
    reporter.user_hash,
    'post',
    reviewPost.id,
    'Seeded report for governance demo',
    3
  );
  const moderationCase = ensureOpenCase(store, report, 'post', reviewPost.id, accused.user_hash);

  return {
    users: {
      moderator,
      juror,
      reporter,
      member,
      accused,
      orgMember
    },
    spaces: {
      public: publicSpace,
      edu: eduSpace,
      org: orgSpace
    },
    posts: {
      welcome: welcomePost,
      review: reviewPost
    },
    case: moderationCase
  };
}
